/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PagamentoSucessoRouteImport } from './routes/pagamento.sucesso'
import { Route as PagamentoFalhaRouteImport } from './routes/pagamento.falha'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiMpWebhookRouteImport } from './routes/api/mp-webhook'
import { Route as ApiGenerateImageRouteImport } from './routes/api/generate-image'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiCaktoWebhookRouteImport } from './routes/api/cakto-webhook'
import { Route as AuthenticatedStudioRouteImport } from './routes/_authenticated/studio'
import { Route as AuthenticatedGaleriaRouteImport } from './routes/_authenticated/galeria'
import { Route as AuthenticatedExplorarRouteImport } from './routes/_authenticated/explorar'
import { Route as AuthenticatedCreditosRouteImport } from './routes/_authenticated/creditos'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as ApiPublicChatAnonRouteImport } from './routes/api/public/chat-anon'
import { Route as ApiPublicCaktoWebhookRouteImport } from './routes/api/public/cakto-webhook'
import { Route as ApiPublicCajupayWebhookRouteImport } from './routes/api/public/cajupay-webhook'
import { Route as AuthenticatedCConversationIdRouteImport } from './routes/_authenticated/c.$conversationId'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoSucessoRoute = PagamentoSucessoRouteImport.update({
  id: '/pagamento/sucesso',
  path: '/pagamento/sucesso',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoFalhaRoute = PagamentoFalhaRouteImport.update({
  id: '/pagamento/falha',
  path: '/pagamento/falha',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMpWebhookRoute = ApiMpWebhookRouteImport.update({
  id: '/api/mp-webhook',
  path: '/api/mp-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateImageRoute = ApiGenerateImageRouteImport.update({
  id: '/api/generate-image',
  path: '/api/generate-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCaktoWebhookRoute = ApiCaktoWebhookRouteImport.update({
  id: '/api/cakto-webhook',
  path: '/api/cakto-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudioRoute = AuthenticatedStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGaleriaRoute = AuthenticatedGaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExplorarRoute = AuthenticatedExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCreditosRoute = AuthenticatedCreditosRouteImport.update({
  id: '/creditos',
  path: '/creditos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicChatAnonRoute = ApiPublicChatAnonRouteImport.update({
  id: '/api/public/chat-anon',
  path: '/api/public/chat-anon',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCaktoWebhookRoute = ApiPublicCaktoWebhookRouteImport.update({
  id: '/api/public/cakto-webhook',
  path: '/api/public/cakto-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCajupayWebhookRoute = ApiPublicCajupayWebhookRouteImport.update({
  id: '/api/public/cajupay-webhook',
  path: '/api/public/cajupay-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCConversationIdRoute =
  AuthenticatedCConversationIdRouteImport.update({
    id: '/c/$conversationId',
    path: '/c/$conversationId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/creditos': typeof AuthenticatedCreditosRoute
  '/explorar': typeof AuthenticatedExplorarRoute
  '/galeria': typeof AuthenticatedGaleriaRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/api/cakto-webhook': typeof ApiCaktoWebhookRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/mp-webhook': typeof ApiMpWebhookRoute
  '/api/tts': typeof ApiTtsRoute
  '/pagamento/falha': typeof PagamentoFalhaRoute
  '/pagamento/sucesso': typeof PagamentoSucessoRoute
  '/c/$conversationId': typeof AuthenticatedCConversationIdRoute
  '/api/public/cajupay-webhook': typeof ApiPublicCajupayWebhookRoute
  '/api/public/cakto-webhook': typeof ApiPublicCaktoWebhookRoute
  '/api/public/chat-anon': typeof ApiPublicChatAnonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/creditos': typeof AuthenticatedCreditosRoute
  '/explorar': typeof AuthenticatedExplorarRoute
  '/galeria': typeof AuthenticatedGaleriaRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/api/cakto-webhook': typeof ApiCaktoWebhookRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/mp-webhook': typeof ApiMpWebhookRoute
  '/api/tts': typeof ApiTtsRoute
  '/pagamento/falha': typeof PagamentoFalhaRoute
  '/pagamento/sucesso': typeof PagamentoSucessoRoute
  '/c/$conversationId': typeof AuthenticatedCConversationIdRoute
  '/api/public/cajupay-webhook': typeof ApiPublicCajupayWebhookRoute
  '/api/public/cakto-webhook': typeof ApiPublicCaktoWebhookRoute
  '/api/public/chat-anon': typeof ApiPublicChatAnonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/creditos': typeof AuthenticatedCreditosRoute
  '/_authenticated/explorar': typeof AuthenticatedExplorarRoute
  '/_authenticated/galeria': typeof AuthenticatedGaleriaRoute
  '/_authenticated/studio': typeof AuthenticatedStudioRoute
  '/api/cakto-webhook': typeof ApiCaktoWebhookRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/mp-webhook': typeof ApiMpWebhookRoute
  '/api/tts': typeof ApiTtsRoute
  '/pagamento/falha': typeof PagamentoFalhaRoute
  '/pagamento/sucesso': typeof PagamentoSucessoRoute
  '/_authenticated/c/$conversationId': typeof AuthenticatedCConversationIdRoute
  '/api/public/cajupay-webhook': typeof ApiPublicCajupayWebhookRoute
  '/api/public/cakto-webhook': typeof ApiPublicCaktoWebhookRoute
  '/api/public/chat-anon': typeof ApiPublicChatAnonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/privacidade'
    | '/termos'
    | '/configuracoes'
    | '/creditos'
    | '/explorar'
    | '/galeria'
    | '/studio'
    | '/api/cakto-webhook'
    | '/api/chat'
    | '/api/generate-image'
    | '/api/mp-webhook'
    | '/api/tts'
    | '/pagamento/falha'
    | '/pagamento/sucesso'
    | '/c/$conversationId'
    | '/api/public/cajupay-webhook'
    | '/api/public/cakto-webhook'
    | '/api/public/chat-anon'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacidade'
    | '/termos'
    | '/configuracoes'
    | '/creditos'
    | '/explorar'
    | '/galeria'
    | '/studio'
    | '/api/cakto-webhook'
    | '/api/chat'
    | '/api/generate-image'
    | '/api/mp-webhook'
    | '/api/tts'
    | '/pagamento/falha'
    | '/pagamento/sucesso'
    | '/c/$conversationId'
    | '/api/public/cajupay-webhook'
    | '/api/public/cakto-webhook'
    | '/api/public/chat-anon'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/privacidade'
    | '/termos'
    | '/_authenticated/configuracoes'
    | '/_authenticated/creditos'
    | '/_authenticated/explorar'
    | '/_authenticated/galeria'
    | '/_authenticated/studio'
    | '/api/cakto-webhook'
    | '/api/chat'
    | '/api/generate-image'
    | '/api/mp-webhook'
    | '/api/tts'
    | '/pagamento/falha'
    | '/pagamento/sucesso'
    | '/_authenticated/c/$conversationId'
    | '/api/public/cajupay-webhook'
    | '/api/public/cakto-webhook'
    | '/api/public/chat-anon'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  TermosRoute: typeof TermosRoute
  ApiCaktoWebhookRoute: typeof ApiCaktoWebhookRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiGenerateImageRoute: typeof ApiGenerateImageRoute
  ApiMpWebhookRoute: typeof ApiMpWebhookRoute
  ApiTtsRoute: typeof ApiTtsRoute
  PagamentoFalhaRoute: typeof PagamentoFalhaRoute
  PagamentoSucessoRoute: typeof PagamentoSucessoRoute
  ApiPublicCajupayWebhookRoute: typeof ApiPublicCajupayWebhookRoute
  ApiPublicCaktoWebhookRoute: typeof ApiPublicCaktoWebhookRoute
  ApiPublicChatAnonRoute: typeof ApiPublicChatAnonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento/sucesso': {
      id: '/pagamento/sucesso'
      path: '/pagamento/sucesso'
      fullPath: '/pagamento/sucesso'
      preLoaderRoute: typeof PagamentoSucessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento/falha': {
      id: '/pagamento/falha'
      path: '/pagamento/falha'
      fullPath: '/pagamento/falha'
      preLoaderRoute: typeof PagamentoFalhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mp-webhook': {
      id: '/api/mp-webhook'
      path: '/api/mp-webhook'
      fullPath: '/api/mp-webhook'
      preLoaderRoute: typeof ApiMpWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-image': {
      id: '/api/generate-image'
      path: '/api/generate-image'
      fullPath: '/api/generate-image'
      preLoaderRoute: typeof ApiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cakto-webhook': {
      id: '/api/cakto-webhook'
      path: '/api/cakto-webhook'
      fullPath: '/api/cakto-webhook'
      preLoaderRoute: typeof ApiCaktoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/studio': {
      id: '/_authenticated/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof AuthenticatedStudioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/galeria': {
      id: '/_authenticated/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof AuthenticatedGaleriaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/explorar': {
      id: '/_authenticated/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof AuthenticatedExplorarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/creditos': {
      id: '/_authenticated/creditos'
      path: '/creditos'
      fullPath: '/creditos'
      preLoaderRoute: typeof AuthenticatedCreditosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/chat-anon': {
      id: '/api/public/chat-anon'
      path: '/api/public/chat-anon'
      fullPath: '/api/public/chat-anon'
      preLoaderRoute: typeof ApiPublicChatAnonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cakto-webhook': {
      id: '/api/public/cakto-webhook'
      path: '/api/public/cakto-webhook'
      fullPath: '/api/public/cakto-webhook'
      preLoaderRoute: typeof ApiPublicCaktoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cajupay-webhook': {
      id: '/api/public/cajupay-webhook'
      path: '/api/public/cajupay-webhook'
      fullPath: '/api/public/cajupay-webhook'
      preLoaderRoute: typeof ApiPublicCajupayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/c/$conversationId': {
      id: '/_authenticated/c/$conversationId'
      path: '/c/$conversationId'
      fullPath: '/c/$conversationId'
      preLoaderRoute: typeof AuthenticatedCConversationIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedCreditosRoute: typeof AuthenticatedCreditosRoute
  AuthenticatedExplorarRoute: typeof AuthenticatedExplorarRoute
  AuthenticatedGaleriaRoute: typeof AuthenticatedGaleriaRoute
  AuthenticatedStudioRoute: typeof AuthenticatedStudioRoute
  AuthenticatedCConversationIdRoute: typeof AuthenticatedCConversationIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedCreditosRoute: AuthenticatedCreditosRoute,
  AuthenticatedExplorarRoute: AuthenticatedExplorarRoute,
  AuthenticatedGaleriaRoute: AuthenticatedGaleriaRoute,
  AuthenticatedStudioRoute: AuthenticatedStudioRoute,
  AuthenticatedCConversationIdRoute: AuthenticatedCConversationIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  TermosRoute: TermosRoute,
  ApiCaktoWebhookRoute: ApiCaktoWebhookRoute,
  ApiChatRoute: ApiChatRoute,
  ApiGenerateImageRoute: ApiGenerateImageRoute,
  ApiMpWebhookRoute: ApiMpWebhookRoute,
  ApiTtsRoute: ApiTtsRoute,
  PagamentoFalhaRoute: PagamentoFalhaRoute,
  PagamentoSucessoRoute: PagamentoSucessoRoute,
  ApiPublicCajupayWebhookRoute: ApiPublicCajupayWebhookRoute,
  ApiPublicCaktoWebhookRoute: ApiPublicCaktoWebhookRoute,
  ApiPublicChatAnonRoute: ApiPublicChatAnonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
